### ISSUE TITLE
Update dependency from `kyazdani42/nvim-web-devicons` to `nvim-tree/nvim-web-devicons`

### ISSUE THREAD

**Issue by raj-magesh** [ghillb/cybu.nvim#14]
I get this error (`Cybu: nvim-web-devicons enabled, but not installed`) on starting Neovim and I assume it's because the repository changed from `kyazdani42/nvim-web-devicons` to `nvim-tree/nvim-web-devicons`.

**Comment by ghillb** [comment]
It should not be an issue if you install via the old reference, as it redirects to the new location.

Could you check if `nvim-tree/nvim-web-devicons` is correctly installed? You can use the following command:
```vim
:lua =require'nvim-web-devicons'.has_loaded()
```
If everything is OK, it should return `true`. If you receive an error, that means you probably need to install  `nvim-tree/nvim-web-devicons` first.

Nonetheless, I have updated all references in the README from `kyazdani42/nvim-web-devicons` to `nvim-tree/nvim-web-devicons`.

**Comment by raj-magesh** [comment]
You were right, thank you! Apparently `packer.nvim` doesn't install dependencies into the same location unless they're explicitly specified as a top-level plugin.
