### ISSUE TITLE
Cycling through last x number of buffers

### ISSUE THREAD

**Issue by andis-sprinkis** [ghillb/cybu.nvim#18]
Bufstop plugin has a "speed" mode which lets user cycle through last specified number of buffers viewed, so I can do things like
- use F2 to F12 keys to back-cycle through the specified number of buffers
- tap \<leader\>\<leader\> to cycle back and then \<leader\>\<leader\> to cycle forward between the last 2 buffers
without displaying a menu.

https://github.com/mihaifm/bufstop

This is fast and puts convenient limit on a list of buffers to cycle through when there are many open.
Any thoughts about implementing a similar approach in this plugin?

**Comment by ghillb** [comment]
>tap <leader><leader> to cycle back and then <leader><leader> to cycle forward between the last 2 buffers without displaying a menu.

That sounds like `:CybuLastusedNext` (just without context window) and I was actually thinking about adding a windowless mode. So this will probably come in a future update.

> use F2 to F12 keys to back-cycle through the specified number of buffers

This sounds certainly interesting, but exceeds the scope that is currently planned for the plugin. I need to think about if and how to add such a feature.
