### ISSUE TITLE
Change the buffer order to most recently used

### ISSUE THREAD

**Issue by primeapple** [ghillb/cybu.nvim#3]
Since you are basically implementing a kind of `Alt-Tab` within Neovim, how would you think of changing the order of the displayed buffers to most recently used. This would then refelect the `Alt-Tab` Behaviour to 100% :)

**Comment by ghillb** [comment]
That sounds like a cool Idea and I will put it on the list for a future release :)

**Comment by ghillb** [comment]
Inspired by [joshuarubin](https://github.com/joshuarubin)'s solution, which is something slightly different (tabs are changed instantaneously, with #4,).

I've added a new cycling mode, which implements the `Alt-Tab` functionality, akin to what web browser do (switch to tab, after selection).

Feel free to test it on the [feat.cycle_last_used](https://github.com/ghillb/cybu.nvim/tree/feat.cycle_last_used) branch.

After installing the branch, you would have to set two new mappings for this:
```
vim.keymap.set("n", "<a-s-tab>", "<plug>(CybuHistoryPrev)")
vim.keymap.set("n", "<a-tab>", "<plug>(CybuHistoryNext)")
```
Beware that there is still a bug, that is inconsistently occurring when triggering the window in short succession. Also the exemplary keys `<a-s-tab>` and `<a-tab>` do not work for all terminals out of the box, and you would have to change them, if this is the case for you.
