### ISSUE TITLE
bug: Current buffer highlight dissapears when you set the terminal transparent

### ISSUE THREAD

**Issue by sergiornelas** [ghillb/cybu.nvim#8]
Hello, thank you for this amazing plugin. 
I use this plugin for setting neovim to transparent: "xiyaowong/nvim-transparent", and when transparency is on, the cybu current buffer line highlight disappears.

**Comment by ghillb** [comment]
Hi, do you use a custom highlight for the current buffer highlight? Example:
```lua
style = {
    highlights = {
      current_buffer = "CustomHL",       -- current / selected buffer
    },
```

If not, try to set one. The [default highlight for the current buffer](https://github.com/ghillb/cybu.nvim/blob/ca7fd7392ae866fbeed1fe0980923206d4f4fcc7/plugin/cybu.lua#L54) just inherits from the "Normal" and "Visual" highlight groups.

`xiyaowong/nvim-transparent` probably manipulates those highlight groups, which results in the effect.

If I misunderstand your issue, please provide a screenshot.

**Comment by sergiornelas** [comment]
That worked. Thanks!
I use this one, it's eye catchy for all my color schemes.
`current_buffer = "rainbowcol7",`
